name: CD Pipeline

on:
  workflow_run:
    workflows: ["DevOps CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Ð£ÑÑ‚Ð°Ð½Ð¾Ð²ÐºÐ° SSH ÐºÐ»ÑŽÑ‡Ð°
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 193.47.42.98 >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ÐŸÐ¾Ð´ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¸Ðµ Ðº ÑÐµÑ€Ð²ÐµÑ€Ñƒ Ð¸ Ð´ÐµÐ¿Ð»Ð¾Ð¹
        run: |
          echo "ðŸš€ ÐŸÐ¾Ð´ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¸Ðµ Ðº ÑÐµÑ€Ð²ÐµÑ€Ñƒ..."
          ssh root@193.47.42.98 "echo \"$(date '+%Y-%m-%d %H:%M:%S')\" >> ~/test.text && bash ~/deploy.hs"

